### Basic authorization.



GET http://{{host}}:{{port}}/api/user/login
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

###

GET http://{{host}}:{{port}}/api/users/all
Accept: application/json



###
GET http://{{host}}:{{port}}/api/username


###
